[예외처리](https://wikidocs.net/30)

try except 예외처리
일반적으로 프로그램 수행 도중에 예외가 발생하면 프로그램은 예외 메시지를 표시하고 자동 종료됩니다.
만일 서버 프로그램처럼 종료되면 안되는 프로그램이라면 예외 처리를 하여 프로그램 종료를 막을 수 있습니다.
예외가 발생할 부분을 try영역에 지정하고 except영역에서 예외를 처리할 코드를 작성해주면 됩니다.


```python
while True:
    try:
        A, B = map(int, input().split())
        print(A+B)
    except:
        break
```


while이 가장 큰 범위이기 때문에 에러가 생기면 반복이 멈춘다.

```python
while True:
    try:
        A, B = map(int, input().split())
        print(A+B)
    except:
        print('error')
```

위와 같으나 break에 대한 언급이 없기 때문에 에러가 생기면 error가 출력된 후, 다시 반복된다.

```python
try:
    while True:
        A, B = map(int, input().split())
        print(A+B)
except:
    print("error")
```

에러가 발생하면 while문을 벗어나 error를 출력하고 종료된다.